#!/usr/bin/env zsh

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  successfully open https://github.com/account/ssh

echo "Fixing permissions ..."
  successfully sudo chown -R `whoami` /usr/local

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

echo "Install basic dependencies"
  successfully brew install fuse4x fuse4x-kext libpng jpeg libtiff

echo "Installing Python and Node"
  successfully brew install python node

echo "Putting Homebrew location earlier in PATH ..."
  successfully echo "
# recommended by brew doctor
export PATH='/usr/local/bin:/usr/local/share/python:/usr/local/share/npm/bin:$PATH'" >> ~/.zshenv
  successfully source ~/.zshenv

echo "Installing GNU Compiler Collection and dependencies ..."
  successfully brew tap homebrew/dupes
  successfully brew install autoconf automake apple-gcc42

echo "Installing libksba, recommended for Ruby 1.9.3 ..."
  successfully brew install libksba

echo "Install python packages"
  successfully pip install --upgrade distribute
  successfully pip install --upgrade pip
  successfully pip install virtualenv
  successfully pip install virtualenvwrapper
  successfully pip install mercurial
  successfully pip install flake8

echo "Install npm packages"
  successfully npm install coffee-script -g

echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgres --no-python
  successfully initdb /usr/local/var/postgres -E utf8

echo "Installing PostGIS, a good open source geo-spatial database extension ..."
  successfully brew install geos proj
  successfully brew install gdal --without-python
  successfully brew install postgis

echo "Installing Redis, a good key-value database ..."
  successfully brew install redis

echo "Installing ack, for searching the contents of files ..."
  successfully brew install ack

echo "Installing ctags, for indexing files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

echo "Installing tmux, for saving project state and switching between projects ..."
  successfully brew install tmux

echo "Installing reattach-to-user-namespace, for copy-paste and RubyMotion compatibility with tmux ..."
  successfully brew install reattach-to-user-namespace

echo "Installing RVM (Ruby Version Manager) and Ruby 1.9.3-p327, which becomes the default ..."
  successfully curl -L https://get.rvm.io | bash -s stable --ruby
  successfully echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshenv
  successfully source ~/.rvm/scripts/rvm

echo "Installing critical Ruby gems for development ..."
  successfully gem install bundler vagrant foreman --no-rdoc --no-ri

echo "More brews"
  successfully brew install macvim
